---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.ingress.name }}-ingress-nginx
    app.kubernetes.io/part-of: nginx-ingress-maintainer
  annotations:
    cert-manager.io/issuer: {{ .Values.issuer.name }}
    {{- if .Values.ingress.whitelist.enabled -}}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .Values.ingress.whitelistSourceRange }}
    {{- end }}
spec:
  # Ingress resources need to have the ingressClassName field set to 
  # the value of the class of the Ingress Controller the user wants to use.
  ingressClassName: {{ .Values.ingress.name }}-nginx
  tls:
   - hosts:
     {{- range .Values.ingress.hosts }}
     - {{ .host }}
     {{- end }}
     secretName: letsencrypt-nginx-{{ .Values.ingress.name }}-app
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      - pathType: {{ .pathType | default "Prefix" }}
        path: {{ .path | default "/" | quote }}
        backend:
          service:
            name: {{ .service }}
            port:
              number: {{ .port | default 80 }}
  {{- end }}
